library(RMySQL)
con = dbConnect(MySQL(), user = 'root', password = '', dbname = 'iris', host = 'localhost')
myQuery <- "select * from miris;"
dfibnu <- dbGetQuery(con, myQuery)
View(dfibnu)
by(dfibnu$petal_width, dfibnu$iris, mean)
by(dfibnu$petal_width, dfibnu$iris, sd)
by(dfibnu$petal_width, dfibnu$iris, summary)
library(ggplot2)
qplot(iris, petal_length, data=dfibnu, geom="boxplot", fill=iris)

con = dbConnect(MySQL(), user = 'root', password = '', dbname = 'iris', host = 'localhost')
myQuery <- "select * from niris;"
dfibnutugas <- dbGetQuery(con, myQuery)
View(dfibnutugas)
by(dfibnutugas$Fare, dfibnutugas$Survived, mean)
by(dfibnutugas$Fare, dfibnutugas$Survived, sd)
by(dfibnutugas$Fare, dfibnutugas$Survived, summary)
library(ggplot2)
qplot(Sex,Survived, data=dfibnutugas, geom="boxplot", fill=Sex)
qplot(Sex,Pclass, data=dfibnutugas, geom="boxplot", fill=Sex)
qplot(Sex,Fare, data=dfibnutugas, geom="boxplot", fill=Sex)
hist(dfibnutugas$Fare[dfibnutugas$Survived=="1"])
hist(dfibnutugas$Fare[dfibnutugas$Survived=="0"])
